
CONST_NONE <- "none"
CONST_POINT <- "point"
CONST_HISTOGRAM <- "histogram"
CONST_LINE <- "line"
CONST_BOXPLOT <- "boxplot"
CONST_DEFAULT_POINT_SIZE <- 1.5
CONST_DEFAULT_LINE_SIZE <- 0.5
CONST_DEFAULT_BINS <- 30
CONST_DEFAULT_THEME <- "theme_gray"
CONST_DEFAULT_THEME_BASE_SIZE <- 11
